### ISSUE TITLE
Add some file

### ISSUE THREAD

**Issue by ShadowGreg** [JobAssistant/job#2]
Please add some file for this repo

**Comment by GregOsetrov85** [comment]
in work

**Comment by GregOsetrov85** [comment]
@[ShadowGreg](https://github.com/ShadowGreg) ShadowGreg merged commit [429f384](https://github.com/JobAssistant/job/commit/429f3841d1883c44dc414965c93845c5acbe92b6) into master [12 minutes ago](https://github.com/JobAssistant/job/pull/1#event-10037351478)
